#!/usr/bin/env bash
#Loops from 1-10 displaying 'bad luck' at 4, 'good luck' at 8
# and 'Best School' for the rem iterations
count=1
while [ $count -le 10 ]
do
  if [ $count -eq 4 ]; then
    echo "bad luck"
  elif [ $count -eq 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi
  ((count++))
done
